name: Build Multi-Arch Images

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Clone openethereum Source Code
        run: |
          git clone -b "v3.1.0" --depth 1 --recursive https://github.com/openethereum/openethereum.git

      - name: Build Multi-Arch Images
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo systemctl restart docker
          docker buildx create --name multi_builder
          docker buildx use multi_builder
          cd openethereum
          docker buildx build -f ../Dockerfile -t xjonathanlei/openethereum:v3.1.0 --platform linux/amd64,linux/arm64 .
          docker tag xjonathanlei/openethereum:v3.1.0 xjonathanlei/openethereum:latest

      - name: Push Multi-Arch Images
        run: |
          docker push xjonathanlei/openethereum:v3.1.0
          docker push xjonathanlei/openethereum:latest
